### DISCUSSION TITLE
Using AI to create package.yml files

### DISCUSSION THREAD

**Discussion by magnusviri** [pkgxdev/pkgx#435] [Ideas]
I've been studying AI and I wondered if it would be possible to fine tune a large language model with the differences between the existing tea package.yml files with the equivalent Homebrew, yum, apt, and Chocolately formula. Then feed the model all of the formula that it doesn't already have to produce package.yml files. My AI knowledge is superficial, so I have no idea how to do this, but I'm going to start learning, just in case someone else way smarter than me doesn't just decide to do it over the weekend or something like that.

**Comment by mxcl** [comment]
I’m sure it’s possible.

However I think we could get better results from just implementing a ruby script to translate Homebrew pkgs. Though the AI approach is potentially WAY LESS work.

Longer term we want our package.yml format to be something pkg authors include in their repos so this effort stops getting duplicated.

**Reply by davdroman** [reply]
> Longer term we want our package.yml format to be something pkg authors include in their repos so this effort stops getting duplicated.

I was going to make a joke suggesting a random standard name "OpenPKG" à la OpenAPI, but then I looked it up and it's already a thing! http://www.openpkg.org/

**Reply by adriens** [reply]
I think I'll makea feature request in that sens to [`jreleaser`](https://jreleaser.org/) for the java ecosystem.

Also, being able to link to sdkman or jbang script could be very useful to add a very larje jvm ecosystem, see

- https://github.com/teaxyz/pantry/issues/810
- https://github.com/teaxyz/pantry/issues/809 
- https://github.com/jreleaser/jreleaser/issues/1280

**Comment by magnusviri** [comment]
I've thought of writing a formula parser also. In fact, I kind of started one but Ruby is towards the bottom of my experience list (I learned it but then never used it...). So I wrote a parser in Perl but didn't get very far.

I sent an email to surgehq.ai and told them what I wanted to do and asked for a quote. I had Marc's email so I CC'ed him. I'm curious what they'll quote me. I know they have free tiers, so yeah, it will be interesting to see what they say. I almost want to do this more because I'm dying to know if it will work.

**Comment by magnusviri** [comment]
SurgeHQ got back to me and said they are looking for annual customers. So basically "no".

I just applied to the GPT-4 waitlist. With 32,000 context tokens, I bet it can do this. I'm going to start cleaning up the brew files and removing stuff that doesn't really convert over (like bottle hashes).

Also, FYI, I'm planning on taking some extended "vacation" from my day job in April to work on this. I'm hoping to also package up stable-diffusion and llama on that same vacation.

**Reply by mfts** [reply]
Did you see the stable diffusion webui script that Max put together in the readme

```
$ git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
$ tea \
  --cd stable-diffusion-webui \
  +python.org~3.10 +pip.pypa.io +gnu.org/wget +protobuf.dev +rust-lang.org \
  ./webui.sh
```

**Reply by magnusviri** [reply]
No! I'll have to check it out!

**Reply by mfts** [reply]
I just fed chat.openai.com with GPT-4 the example package.yml from brewkit and asked it to give me the instructions for `libx11`

It's of course not perfect yet, but with clearer instructions, it might get there:

```
distributable:
  url: https://www.x.org/releases/individual/lib/libX11-{{version}}.tar.gz
  strip-components: 1

versions:
  github: freedesktop/xorg-libX11/tags

strip: /^v/

dependencies:
  tea.xyz/xorg/proto/xproto: ^7.0.31
  tea.xyz/xorg/proto/xextproto: ^7.3.0
  tea.xyz/xorg/proto/kbproto: ^1.0.7

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    tea.xyz/xorg/util/macros: ^1.19.3
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }} install
  env:
    ARGS:
      - --prefix="{{prefix}}"

provides:
  - lib/libX11.so
  - lib/libX11.a
  - include/X11

test:
  dependencies:
    tea.xyz/xorg/lib/libx11: '*'
  script:
    test "$(pkg-config --modversion x11)" = {{version}}
```
