### DISCUSSION TITLE
dev env cd run commands

### DISCUSSION THREAD

**Discussion by atomraymaker** [pkgxdev/pkgx#871] [Ideas]
I really like that I can cd into a directory and have packages and env vars in scope. 

In the case of a package like postgres it would be nice to be able to start and stop this when moving in and out of a directory also. 

This could be done by parsing this from the config:

```
dependencies: postgresql.org@15.2.0 go.dev@1.21.4
env:
  DB_HOST: localhost
  DB_NAME: postgres
  DB_PORT: 5433
  DB_USER: postgres
commands:
  in:
    - make db_start
    - make db_migrate
  out:
    - make db_stop
```

This would shell out to run these commands once the deps and env have been loaded. Then just print out any messages or errors from these commands.
