### ISSUE TITLE
Where is markdown blocks execition engine?

### ISSUE THREAD

**Issue by abitrolly** [pkgxdev/pkgx#1015]
I remember there was a piece of code that executed and probably updated markdown blocks. Is it still available somewhere? Would like to reuse it for some troubleshooting. Tired of pasting code blocks in dead documents that need to be updated when new versions of tools inside released.

**Comment by jhheider** [comment]
Are you looking for `xcfile.dev`?

**Comment by abitrolly** [comment]
@jhheider thanks, but it looks like it is meant to run tasks, and doesn't update the output in markdown files (need deeper checks). I remember this repo used to run the script that updated and/or validated command output.

**Comment by jhheider** [comment]
Hm, I'm not sure what that would be. We have task runners like xc and just and, of course, make, packages. And stuff link amber-lang, shellcheck and other tools to make scripting reliable. But I don't specifically know of a tool for updating and validating scripts. `pier` might be the closest, but I don't think it's what you're looking for.

**Comment by abitrolly** [comment]
I knew it, but lost. I think it was used for unit testing or something. Got this so far.

* https://github.com/joerdav/xc - markdown task runner, allows to select code block to run
* https://github.com/pawamoy/markdown-exec - executes code blocks and renders them 

Where is this `pier`?

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/blob/main/projects/crates.io/pier/package.yml

**Comment by abitrolly** [comment]
Yea, organizing shell snippets is a bit different task.

**Comment by abitrolly** [comment]
Found something extracted from Go internals https://github.com/rogpeppe/go-internal/tree/master/cmd/testscript

**Comment by abitrolly** [comment]
Found two other project that execute test files combining commands with expected output.

* https://pkg.go.dev/github.com/brimdata/zed/mdtest - executes and compares markdown
* https://github.com/rogpeppe/go-internal/tree/master/cmd/testscript - executes .txtar files which are easier to update

I packed `testscript` for Homebrew. Now I need to see what it takes for `pkgx` to run it.

**Comment by jhheider** [comment]
very little; i should be able to do it today.

**Comment by abitrolly** [comment]
```yaml
test:
  - run: test "$(testscript $FIXTURE)" = "PASS"
    fixture:
      extname: txtar
      contents: |
        exec echo hello!
        stdout hello!
```

Maybe `pkgx` should adopt `txtar` format too. :D

```yaml
testscript: |
  exec testscript hello.txtar
  stdout PASS

  -- hello.txtar --
  exec echo hello!
  stdout hello!
```

**Comment by jhheider** [comment]
there's an even simpler solution:

```yaml
interprets:
  extensions: txtar
  args: testscript

test:
  dependencies:
    pkgx.sh: 1
  script:
    - run: test "$(pkgx $FIXTURE)" = "PASS"
      fixture:
        extname: txtar
        contents: |
          exec echo hello!
          stdout hello!

```
