### ISSUE TITLE
getting `libcrypto.so.1.1 ... No such file or directory` for `pkgx npx ...`

### ISSUE THREAD

**Issue by eifr** [pkgxdev/pkgx#1085]
Running pkgx 2.1 on kde plasma (zsh) and I keep getting `node: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory` when trying to run `pkgx npx ..` or when trying to run nushell: `/home/eifr/.pkgx/nushell.sh/v0.101.0/bin/nu: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by jhheider** [comment]
```yaml
dependencies:
  # prior builds of nodejs used our icu4c
  unicode.org: ^71
  openssl.org: 1.1
  zlib.net: 1
  linux:
    gnu.org/gcc/libstdcxx: '*' # libstdc++, since 22.2.0
```
it definitely *depends* on node... i saw a similar report in the last week. i assume `pkgx +nodejs.org | grep openssl.org` works just fine, which suggests there's something odd about the shim.
