### ISSUE TITLE
Python setup fails in amazon linux 2 self hosted github runner

### ISSUE THREAD

**Issue by kishaningithub** [pkgxdev/pkgx#833]
## Context
I am using self hosted github runners which use amazon linux 2 as their operating system

## Github action yaml

```yaml
steps:
    - uses: actions/checkout@v3
    - uses: pkgxdev/setup@v1
      with:
        +: python@3.8
    - name: python version
      run: |
        python --version
        python3 --version
```

## Error

The above action fails with the following error.

```
python: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/.pkgx/python.org/v3.8.18/bin/../lib/libpython3.8.so.1.0)

python: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/ec2-user/.pkgx/python.org/v3.8.18/bin/../lib/libpython3.8.so.1.0)
```
