### ISSUE TITLE
parse issue freedesktop.org/cppunit

### ISSUE THREAD

**Issue by leonsilicon** [pkgxdev/pkgx#970]
Running `pkgx install freedesktop.org/cppunit` gives the following error:
```
pkgx install freedesktop.org/cppunit
× parse error freedesktop.org/cppunit
│ this is a serious issue. please report the bug
╰─➤ https://github.com/pkgxdev/pkgx/issues/new?title=parse+issue+freedesktop.org/cppunit
```

**Comment by jhheider** [comment]
```shell
$ pkgx install freedesktop.org/cppunit
pkgx: installed: ~/.local/bin/cppunit-config
pkgx: installed: ~/.local/bin/DllPlugInTester
$ rm ~/.local/bin/cppunit-config 
$ rm ~/.local/bin/DllPlugInTester 
```
#worksforme

to troubleshoot, can you paste in the contents of your
- [Darwin]: ~/Library/Application\ Support/pkgx/pantry/projects/freedesktop.org/cppunit/package.yml
- [Linux]: ~/.local/state/pkgx/pantry/projects/freedesktop.org/cppunit/package.yml

it should specifically match
```yaml
distributable:
  url: http://dev-www.libreoffice.org/src/cppunit-{{version}}.tar.gz
  strip-components: 1

versions:
  url: https://dev-www.libreoffice.org/src/cppunit/
  match: /cppunit-\d+\.\d+\.\d+.tar.gz/
  strip:
    - /^cppunit-/
    - /\.tar\.gz$/

build:
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }} install
  env:
    ARGS:
      - --prefix="{{prefix}}"
    linux/aarch64:
      ARGS:
        - --build=aarch64-unknown-linux-gnu

provides:
  - bin/cppunit-config
  - bin/DllPlugInTester

test: cppunit-config --version | grep {{version}}
```
exactly.

assuming it doesn't (though we'll be interested to see what it does contain), `pkgx --sync` should refresh it.
